### ISSUE TITLE
Json decode error

### ISSUE THREAD

**Issue by Arp-G** [brainlid/langchain_demo#2]
Hi, thanks for this demo repo. I really liked the blog post and wanted to try the code myself but I faced issues.

I cloned the repo and ran `mix setup` then I created an open AI secret key.
The Key works well when I try this request
```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <OPENAI_KEY>" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "What is love?"}],
     "temperature": 0.7
   }'
```
I added the key to the environment and tried using the app but whenever I send a message I get an error like so
```
[error] Task #PID<0.639.0> started from #PID<0.637.0> terminating
** (FunctionClauseError) no function clause matching in LangChain.ChatModels.ChatOpenAI.do_process_response/1
    (langchain 0.1.1) lib/chat_models/chat_open_ai.ex:413: LangChain.ChatModels.ChatOpenAI.do_process_response({:error, %Jason.DecodeError{position: 0, token: nil, data: <<31, 139, 8, 0, 0, 0, 0, 0, 0, 3, 76, 143, 177, 110, 3, 33, 16, 68, 251, 251, 138, 17, 181, 185, 139, 173, 40, 150, 248, 134, 148, 233, 207, 8, 54, 6, 9, 88, 12, 123, 78, 44, 203, 255, 30, ...>>}})
    (elixir 1.15.0) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (langchain 0.1.1) lib/chat_models/chat_open_ai.ex:346: LangChain.ChatModels.ChatOpenAI.decode_streamed_data/1
    (langchain 0.1.1) lib/chat_models/chat_open_ai.ex:262: anonymous fn/4 in LangChain.ChatModels.ChatOpenAI.do_api_request/4
    (finch 0.16.0) lib/finch/http1/conn.ex:243: Finch.Conn.receive_response/8
    (finch 0.16.0) lib/finch/http1/conn.ex:120: Finch.Conn.request/6
    (finch 0.16.0) lib/finch/http1/pool.ex:45: anonymous fn/8 in Finch.HTTP1.Pool.request/5
    (nimble_pool 1.0.0) lib/nimble_pool.ex:349: NimblePool.checkout!/4
    (finch 0.16.0) lib/finch/http1/pool.ex:38: Finch.HTTP1.Pool.request/5
    (finch 0.16.0) lib/finch.ex:306: anonymous fn/6 in Finch.stream/5
    (telemetry 1.2.1) /Users/arpan/dev/others/langchain_demo/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (langchain 0.1.1) lib/chat_models/chat_open_ai.ex:288: anonymous fn/6 in LangChain.ChatModels.ChatOpenAI.do_api_request/4
    (req 0.4.4) lib/req/request.ex:991: Req.Request.run_request/1
    (req 0.4.4) lib/req/request.ex:936: Req.Request.run/1
    (langchain 0.1.1) lib/chat_models/chat_open_ai.ex:318: LangChain.ChatModels.ChatOpenAI.do_api_request/4
    (langchain 0.1.1) lib/chat_models/chat_open_ai.ex:184: LangChain.ChatModels.ChatOpenAI.call/4
    (langchain 0.1.1) lib/chains/llm_chain.ex:204: LangChain.Chains.LLMChain.do_run/1
    (langchain 0.1.1) lib/chains/llm_chain.ex:165: LangChain.Chains.LLMChain.run/2
    (langchain_demo 0.1.0) lib/langchain_demo_web/live/conversation_live/show.ex:316: anonymous fn/2 in LangChainDemoWeb.ConversationLive.Show.run_chain/1
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/async.ex:77: Phoenix.LiveView.Async.do_async/5
Function: #Function<8.8496444/0 in Phoenix.LiveView.Async.run_async_task/4>
    Args: []
```

**Comment by brainlid** [comment]
Oddly, I still haven't hit this error myself. Regardless, it was fixed in the latest v0.1.2 of langchain. I've updated the demo's deps for it.

Try it again and let me know if you still have issues.

**Comment by Arp-G** [comment]
I took a pull but still facing this error 😞 

```
[error] Received invalid JSON: %Jason.DecodeError{position: 0, token: nil, data: <<31, 139, 8, 0, 0, 0, 0, 0, 0, 3, 76, 143, 177, 110, 3, 33, 16, 68, 251, 251, 138, 17, 181, 185, 139, 173, 40, 150, 248, 134, 148, 233, 207, 8, 54, 6, 9, 88, 12, 123, 78, 44, 203, 255, 30, 9, 23, ...>>}
[error] Error during chat call. Reason: "Received invalid JSON: %Jason.DecodeError{position: 0, token: nil, data: <<31, 139, 8, 0, 0, 0, 0, 0, 0, 3, 76, 143, 177, 110, 3, 33, 16, 68, 251, 251, 138, 17, 181, 185, 139, 173, 40, 150, 248, 134, 148, 233, 207, 8, 54, 6, 9, 88, 12, 123, 78, 44, 203, 255, 30, 9, 23, ...>>}"
```

**Comment by brainlid** [comment]
@Arp-G Can you provide more of an example? You can turn on `verbose: true` (the agent demo is stubbed with `verbose: false` so it should be easy to find. 

I'm not clear on what is happening or where the error is.

**Comment by Arp-G** [comment]
The verbose option did not log anything useful. So I did this

I added this
![image](https://github.com/brainlid/langchain_demo/assets/39219943/33c0af63-dd07-416d-9f50-5919c1b26d55)
over [here](https://github.com/brainlid/langchain/blob/f4b2aef818d33c4ae8a05cf166d675f4b12312f5/lib/chat_models/chat_open_ai.ex#L336)

Which printed this
```
<<31, 139, 8, 0, 0, 0, 0, 0, 0, 3, 76, 143, 177, 110, 3, 33, 16, 68, 251, 251,
  138, 17, 181, 185, 139, 173, 40, 150, 248, 134, 148, 233, 207, 8, 54, 6, 9,
  88, 12, 123, 78, 44, 203, 255, 30, 9, 23, 113, 57, 79, 179, 59, 51, 247, 9, 0,
  20, 181, 198, 77, 25, 220, 135, 28, 40, 83, 239, 246, 76, 202, 64, 125, 5, 66,
  102, 79, 9, 167, 115, 21, 253, 126, 130, 103, 234, 40, 44, 160, 223, 216, 5,
  220, 112, 227, 13, 158, 7, 11, 246, 74, 176, 206, 81, 239, 16, 70, 148, 25,
  159, 100, 91, 65, 230, 70, 6, 65, 164, 118, 179, 44, 129, 82, 157, 185, 82,
  177, 113, 118, 156, 23, 42, 139, 109, 18, 93, 162, 190, 28, 247, 111, 135,
  143, 227, 65, 7, 254, 209, 206, 22, 29, 245, 243, 159, 30, 249, 179, 218, 253,
  247, 148, 91, 29, 37, 99, 185, 218, 20, 253, 218, 232, 178, 81, 151, 245, 57,
  233, 197, 88, 109, 179, 89, 25, 148, 45, 165, 23, 236, 216, 143, 251, 49, 112,
  45, 44, 235, 55, 111, 197, 171, 225, 120, 76, 143, 233, 15, 0, 0, 255, 255, 3,
  0, 137, 218, 26, 212, 35, 1, 0, 0>>
```

The response from open AI API is not proper JSON (maybe because we are streaming the response?).
I haven't checked in detail, but we trying to run `Jason.decode/1` on this binary leading to the error

**Comment by mitcheaton1** [comment]
I was getting the same Jason.decode error. I set streaming to false, and then instead of the json error I was told i dont have access to gpt-4. i set streaming back to true, and changed the model to 3.5 and it works. 

```
LLMChain.new!(%{
  llm:
    ChatOpenAI.new!(%{
      model: "gpt-3.5-turbo",
      # don't get creative with answers
      temperature: 0,
      request_timeout: 60_000,
      stream: true
    }),
  custom_context: %{
    live_view_pid: self(),
    current_user: socket.assigns.current_user
  },
  verbose: true
})
 ```

**Comment by brainlid** [comment]
I wonder if you actually don't have API access to gpt-4 yet. When I first started with the API access, I wasn't given gpt-4 access for some time.

My guess is that's what it is.

**Comment by brainlid** [comment]
@mitcheaton1 Do you have access to gpt-4 here?

https://platform.openai.com/playground?mode=chat&model=gpt-4

On the right side, choose "Chat", then the model option is gpt-4. If I remember, gpt-4 wasn't an option there for me until they approved it. Can't remember if I had to request API access to gpt-4 or not. I think so. 

I appreciate the help testing this as I'm sure other's will hit it as well.

**Comment by Arp-G** [comment]
> I wonder if you actually don't have API access to gpt-4

Thanks this was exactly the problem, I did not have access to gpt-4. They also updated [here](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4).

I switched to `gpt-3.5-turbo` and it's working well.

Thanks for the support guys :)

**Comment by mitcheaton1** [comment]
> @mitcheaton1 Do you have access to gpt-4 here?
> 
> https://platform.openai.com/playground?mode=chat&model=gpt-4
> 
> On the right side, choose "Chat", then the model option is gpt-4. If I remember, gpt-4 wasn't an option there for me until they approved it. Can't remember if I had to request API access to gpt-4 or not. I think so.
> 
> I appreciate the help testing this as I'm sure other's will hit it as well.

Yes, it's an access issue. 

![Screenshot 2023-11-02 at 8 41 24 AM](https://github.com/brainlid/langchain_demo/assets/218058/6fa242d5-99be-4b48-9ceb-aa6f6acf6672)
